K8S_PLURALS = {
    "Pod": "pods",
    "Service": "services",
    "ConfigMap": "configmaps",
    "Secret": "secrets",
    "Node": "nodes",
    "Namespace": "namespaces",
    "Event": "events",
    "Endpoints": "endpoints",
    "Deployment": "deployments",
    "StatefulSet": "statefulsets",
    "DaemonSet": "daemonsets",
    "ReplicaSet": "replicasets",
    "Job": "jobs",
    "CronJob": "cronjobs",
    "Ingress": "ingresses",
    "StorageClass": "storageclasses",
    "EndpointSlice": "endpointslices",
    "NetworkPolicy": "networkpolicies",
    "PersistentVolumeClaim": "persistentvolumeclaims",
    "ClusterRoleBinding": "clusterrolebindings",
    "ControllerRevision": "controllerrevisions",
    "RoleBinding": "rolebindings",
    "ServiceAccount": "serviceaccounts",
    "ClusterRole": "clusterroles",
    "Role": "roles",
    "CustomResourceDefinition": "customresourcedefinitions",
}
